# Addestriamo una rete per convertire i gradi Celsius in gradi Fahrenheit
## Fahrenheit = 32 + 1.8 * Celsius

In [14]:
from sklearn import datasets
import pandas as pd
import seaborn as sns
import numpy as np

In [15]:
n_campioni = 100
celsius = np.random.uniform(30,50,n_campioni)
print(celsius)

[38.92053766 42.48668147 44.50668886 36.07557259 32.86235471 35.70974392
 30.10250824 42.64039504 33.11444807 45.20270876 48.92486639 41.5884615
 35.06920984 38.82339077 31.24692039 40.03264872 36.41633078 44.3726623
 42.71509147 44.72472211 43.16495299 31.390766   45.70367558 41.47686059
 39.53280083 30.98026349 35.91576856 38.76820933 31.57169628 43.12389821
 32.71846976 40.34665812 42.98769766 37.53096152 33.90501531 30.96103588
 42.86401275 46.94562186 44.67339892 40.02719201 47.83091433 43.8580406
 41.8936086  48.2458764  32.85083157 35.83697568 35.20935191 38.37366599
 41.46502869 34.16025635 44.86860721 30.38415839 40.95563031 35.26788597
 45.30649189 44.9585367  44.00640007 39.52397385 31.53848195 39.49301302
 36.73586165 42.33483765 41.93152824 39.40122718 32.0298752  30.99419155
 34.67276213 49.09544662 49.07074653 31.71247985 33.0047854  45.81354767
 31.46010279 34.85150009 46.74165124 30.49533104 36.91028103 48.95133095
 34.20175322 33.61285641 32.48183681 34.63915729 45.82

In [16]:
fahrenheit = 32 + 1.8*celsius
print(fahrenheit)

[102.0569678  108.47602664 112.11203994  96.93603066  91.15223848
  96.27753906  86.18451483 108.75271107  91.60600652 113.36487576
 120.06475951 106.8592307   95.12457771 101.88210339  88.24445671
 104.05876769  97.5493954  111.87079214 108.88716465 112.5044998
 109.69691537  88.50337881 114.26661605 106.65834906 103.1590415
  87.76447428  96.64838341 101.7827768   88.8290533  109.62301677
  90.89324557 104.62398461 109.37785579  99.55573073  93.02902756
  87.72986459 109.15522295 116.50211934 112.41211805 104.04894561
 118.09564579 110.94447307 107.40849548 118.84257753  91.13149683
  96.50655623  95.37683343 101.07259879 106.63705165  93.48846143
 112.76349297  86.6914851  105.72013456  95.48219474 113.5516854
 112.92536606 111.21152013 103.14315293  88.7692675  103.08742344
  98.12455097 108.20270778 107.47675084 102.92220893  89.65377536
  87.7895448   94.41097184 120.37180392 120.32734375  89.08246372
  91.40861371 114.46438581  88.62818503  94.73270017 116.13497224
  86.89159587

In [17]:
X = celsius.reshape(-1,1)
y = fahrenheit
print(X[:5], '\n')
print(y[:5])

[[38.92053766]
 [42.48668147]
 [44.50668886]
 [36.07557259]
 [32.86235471]] 

[102.0569678  108.47602664 112.11203994  96.93603066  91.15223848]


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=1) #train_size = percentuale di valori che vanno nel train (70%), il resto va nel test

In [19]:
from sklearn.neural_network import MLPRegressor

regr = MLPRegressor(random_state=1, activation='identity',max_iter=500, hidden_layer_sizes=(), solver='lbfgs')

In [20]:
regr.fit(X_train, y_train)

MLPRegressor(activation='identity', hidden_layer_sizes=(), max_iter=500,
             random_state=1, solver='lbfgs')

In [21]:
regr.predict([[0]])

array([32.00000333])

In [22]:
from sklearn.metrics import mean_absolute_error

print("Train")
predictions = regr.predict(X_train)
mae = mean_absolute_error(predictions, y_train)
print(f"mae: {mae:.10f}")
print(regr.score(X_train, y_train))

print("Train")
predictions = regr.predict(X_test)
mae = mean_absolute_error(predictions, y_test)
print(f"mae: {mae:.10f}")
print(regr.score(X_test, y_test))

Train
mae: 0.0000004004
0.9999999999999978
Train
mae: 0.0000004021
0.9999999999999978


In [23]:
np.set_printoptions(precision=10, suppress=True)
print(regr.predict(X_test)-y_test)

[ 0.0000005655 -0.0000003375  0.0000001357  0.0000003819 -0.0000001757
 -0.0000004466 -0.0000003182 -0.0000005703  0.000000631   0.0000006921
 -0.0000003135 -0.0000000768 -0.0000004155 -0.0000001558  0.0000007441
 -0.0000003288 -0.0000001039  0.0000005341  0.0000004191 -0.0000008341
 -0.0000004581  0.0000003638  0.000000267  -0.0000002389 -0.0000004766
  0.000000695  -0.0000005487  0.0000000304  0.0000003333 -0.0000004722]


In [24]:
regr.coefs_

[array([[1.7999999149]])]

In [26]:
regr.intercepts_

[array([32.0000033304])]

In [30]:
from joblib import dump, load

dump(regr, "fahrenheit.joblib")

modelloImportato = load('fahrenheit.joblib')

print(modelloImportato.predict(X_test))

[ 90.4673068295 109.5637716791  99.5557308638  94.3504834967
 106.1412894144 111.8707916952 109.1552226309 114.4851478778
  89.0824643527  87.7895454905 109.0546851467 104.0489455378
 111.2115197189 105.7201344087  86.6914858451 109.3778554658
 104.6239845061  91.1314973664  93.5631562149 120.0647586768
 112.1120394829  94.7327005344  96.7798124828 107.4767506012
 112.5044993249  87.7298652858 114.0282615184 101.7827768278
  95.3768337631 112.4121175766]
