# Esercizio 1.	
Due giocatori si affrontano in una partita a dadi: ogni volta che un giocatore ottiene un numero maggiore del suo rivale guadagna un punto, mentre se entrambi i giocatori ottengono lo stesso numero guadagnano mezzo punto ciascuno. 
1.	Simulare una partita di 100 lanci e registra i risultati di 10 partite utilizzano Numpy.

In [ ]:
numero_lanci = 100
numero_partite = 10
lanci_giocatore1 = np.random.randint(1,7,(numero_partite,numero_lanci))
lanci_giocatore2 = np.random.randint(1,7,(numero_partite,numero_lanci))
print(lanci_giocatore1[:5,:10])
print(lanci_giocatore2[:5,:10])

punteggio_giocatore1 = np.sum(lanci_giocatore1>lanci_giocatore2, axis=1) + 0.5* np.sum(lanci_giocatore1==lanci_giocatore2, axis=1)
punteggio_giocatore2 = np.sum(lanci_giocatore2>lanci_giocatore1, axis=1) + 0.5* np.sum(lanci_giocatore1==lanci_giocatore2, axis=1)
print(f"Punteggio giocatore 1: {punteggio_giocatore1}")
print(f"Punteggio giocatore 2: {punteggio_giocatore2}")
vittorie_giocatore1 = np.sum(punteggio_giocatore1 > punteggio_giocatore2)
print(f"Il giocatore 1 vince {vittorie_giocatore1} volte")

2. Se un giocatore utilizzasse un dado truccato in cui il 5 e il 6 avessero una probabilità doppia di uscire rispetto agli altri numeri, ce ne potremmo accorgere? Simula questa situazione e giustifica le tue risposte

In [ ]:
# il giocatore 1 ha un dado truccato
numero_lanci = 100
numero_partite = 10
lanci_giocatore1 = np.random.choice(range(1,7),p=[1/8,1/8,1/8,1/8,2/8,2/8],
                                    size=(numero_partite,numero_lanci))
lanci_giocatore2 = np.random.randint(1,7,(numero_partite,numero_lanci))
print(lanci_giocatore1[:5,:10])
print(lanci_giocatore2[:5,:10])

punteggio_giocatore1 = np.sum(lanci_giocatore1>lanci_giocatore2, axis=1) + 0.5* np.sum(lanci_giocatore1==lanci_giocatore2, axis=1)
punteggio_giocatore2 = np.sum(lanci_giocatore2>lanci_giocatore1, axis=1) + 0.5* np.sum(lanci_giocatore1==lanci_giocatore2, axis=1)
print(f"Punteggio giocatore 1: {punteggio_giocatore1}")
print(f"Punteggio giocatore 2: {punteggio_giocatore2}")
vittorie_giocatore1 = np.sum(punteggio_giocatore1 > punteggio_giocatore2)
print(f"Il giocatore 1 vince {vittorie_giocatore1} volte")

# Esercizio 2.
In una fabbrica di cuscinetti a sfera, le 5 macchine lavorano 24 su 24. 
È presente un sistema che memorizza il numero di pezzi prodotti ogni minuto da ognim acchina. Ieri ha memorizzato i dati nel file **misurazioni.csv** allegato.

1. Carica i dati in un vettore di Numpy

In [ ]:
#creazione dei dati
import string

num_misurazioni = 24 * 60 
media = [40, 38, 36, 41, 42]
dev = [4, 2, 3, 1, 3] # intera perchè devo generare numeri interi
num_macchine = len(media)

misurazioni = []
for m,d in zip(media, dev):
    misurazioni.append(np.round(np.random.normal(m, d, (num_misurazioni,))))
misurazioni = np.array(misurazioni, int)
print(misurazioni)
np.savetxt('misurazioni.csv', misurazioni, delimiter=",", fmt='%d')

In [64]:
#carico i dati
dati = []
with open('misurazioni.csv', "r") as file:
    for riga in file.readlines():
            dati.append(riga[:-1].split(","))
misurazioni = np.array(dati,int)
print(misurazioni)

[[41 41 44 ... 38 37 38]
 [37 40 40 ... 37 43 37]
 [36 37 34 ... 36 35 35]
 [41 41 41 ... 42 40 42]
 [39 40 45 ... 44 48 40]]


2. Visualizzare per ogni macchina:
    - il numero totale di pezzi prodotti nella giornata;
    - la media e la deviazione standard dei pezzi prodotti, 
    - il numero minimo e massimo di pezzi prodotti in un minuto
L'output da ottenere è il seguente
![outpu](output.png)

In [70]:
#calcolo statistiche
num_macchine, num_misurazioni = misurazioni.shape

print("totale giornata\t\t", dict(zip(range(num_macchine), misurazioni.sum(axis=1))))
print("media giornata\t\t", dict(zip(range(num_macchine), np.round(misurazioni.mean(axis=1),2))))
print("deviazione\t\t", dict(zip(range(num_macchine), np.round(misurazioni.std(axis=1),2))))
print("numero minimo di pezzi\t", dict(zip(range(num_macchine), misurazioni.min(axis=1))))
print("numero massimo di pezzi\t", dict(zip(range(num_macchine), misurazioni.max(axis=1))))

totale giornata		 {0: 57679, 1: 54694, 2: 52130, 3: 59047, 4: 60469}
media giornata		 {0: 40.05, 1: 37.98, 2: 36.2, 3: 41.0, 4: 41.99}
deviazione		 {0: 4.09, 1: 2.09, 2: 2.91, 3: 1.04, 4: 3.02}
numero minimo di pezzi	 {0: 28, 1: 32, 2: 26, 3: 38, 4: 33}
numero massimo di pezzi	 {0: 56, 1: 45, 2: 47, 3: 45, 4: 53}


3.	Qual è la macchina che ha una produzione più costante, ovvero tende a produrre sempre gli stessi pezzi al minuto? Rispondi nella cella del tuo notebook motivando la risposta.

4. Supponiamo che le macchine inviino per errore un valore -1 con le seguenti probabilità:

- macchina 0: 2%
- macchina 1: 1%
- macchina 2: 3%
- macchina 3: 2%
- macchina 4: 1%

Quali sarebbero i possibili dati memorizzati nel file? Crea il possibile vettore Numpy corrispondente

In [71]:
perc_errori = np.array([0.02, 0.01, 0.03, .02, .01])
errore = -1

num_errori = np.array(num_misurazioni * perc_errori, np.uint)
print("errori",num_errori)
indici = []
for e in num_errori:
    indici.append(np.random.choice(range(num_misurazioni),
                          size=(e), replace=False).tolist())
#print(indici)

misurazioniErrori = np.copy(misurazioni)
for i in range(num_macchine):
    #misurazioniErrori[np.arange(num_macchine).reshape(num_macchine,1),indici] = -1
    misurazioniErrori[i,indici[i]] = -1
print(misurazioniErrori)

errori [28 14 43 28 14]
[[41 41 44 ... 38 37 38]
 [37 40 40 ... 37 43 37]
 [36 37 34 ... 36 35 35]
 [41 41 41 ... 42 40 42]
 [39 40 45 ... 44 48 40]]


5. Secondo gli standard dei produttori delle macchine, se questi errori vengono inviati per più di 10 volte in un minuto, il modulo di invio deve essere riparato. Con i dati da te modificati, su quali macchine bisognerebbe riparare il modulo?

(Suggerimento: ricordati che l'indice del vettore corrisponde al minuto in cui è avvenuta la registrazione del valore errato. Pensa quindi a cosa corrisponde la differenza tra due indici)

In [73]:
#controllo finestra di errore
for i,m in zip(range(num_macchine),misurazioniErrori):
    posizione_errori =  np.argwhere(m==errore)
    print(posizione_errori[:5].flatten())
    distanza_errori = (np.roll(posizione_errori,-1)-posizione_errori)[:-1]
    print(distanza_errori[:5].flatten())

    if np.sum(distanza_errori<=60) >= 10:
        print(f"Macchina {i} da riparare!")

[ 34  68 101 147 166]
[34 33 46 19 42]
Macchina 0 da riparare!
[ 74 315 422 467 547]
[241 107  45  80  14]
[30 58 72 77 82]
[28 14  5  5 13]
Macchina 2 da riparare!
[ 37  78 157 224 237]
[41 79 67 13  2]
Macchina 3 da riparare!
[184 250 372 384 783]
[ 66 122  12 399  98]


# Esercizio 3
Crea con Numpy le coordinate dei 5 vertici di 3 **linee spezzate aperte**, con x e y appartenenti all'intervallo [-10, 10]
![linee spezzate](lineeSpezzate.png)

In [74]:
import numpy as np

n_vertici = 5
n_linee = 3

linee = np.round(np.random.uniform(0,10, size = (n_linee,n_vertici,2) ),2)
print(linee)

[[[9.22 4.84]
  [8.11 0.3 ]
  [7.29 2.26]
  [0.34 1.55]
  [8.95 0.4 ]]

 [[4.99 4.4 ]
  [4.66 3.02]
  [3.03 0.16]
  [8.61 6.88]
  [9.55 8.34]]

 [[6.07 2.51]
  [4.57 3.36]
  [2.52 4.22]
  [3.77 1.61]
  [3.94 6.35]]]


1. Calcola la lunghezza totale di ogni spezzata

In [75]:
sx = np.roll(linee,-1, axis=1)[:,:-1]
l =linee[:,:-1]
print("diff",l-sx)
print("pot",(l-sx)**2)
print("sum",np.sum((l-sx)**2, axis=-1))
print("sqrt",np.sqrt(np.sum((l-sx)**2, axis=-1)))

ris= np.sum(np.sqrt(np.sum((l-sx)**2, axis=-1)),axis=-1)

print("tot",ris)


diff [[[ 1.11  4.54]
  [ 0.82 -1.96]
  [ 6.95  0.71]
  [-8.61  1.15]]

 [[ 0.33  1.38]
  [ 1.63  2.86]
  [-5.58 -6.72]
  [-0.94 -1.46]]

 [[ 1.5  -0.85]
  [ 2.05 -0.86]
  [-1.25  2.61]
  [-0.17 -4.74]]]
pot [[[1.23210e+00 2.06116e+01]
  [6.72400e-01 3.84160e+00]
  [4.83025e+01 5.04100e-01]
  [7.41321e+01 1.32250e+00]]

 [[1.08900e-01 1.90440e+00]
  [2.65690e+00 8.17960e+00]
  [3.11364e+01 4.51584e+01]
  [8.83600e-01 2.13160e+00]]

 [[2.25000e+00 7.22500e-01]
  [4.20250e+00 7.39600e-01]
  [1.56250e+00 6.81210e+00]
  [2.89000e-02 2.24676e+01]]]
sum [[21.8437  4.514  48.8066 75.4546]
 [ 2.0133 10.8365 76.2948  3.0152]
 [ 2.9725  4.9421  8.3746 22.4965]]
sqrt [[4.67372442 2.12461761 6.98617206 8.68646073]
 [1.41890803 3.29188396 8.73468946 1.73643313]
 [1.72409396 2.22308344 2.89389012 4.74304754]]
tot [22.47097482 15.18191458 11.58411507]
