## Disegnare un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [2]:
import numpy as np
'''
def m(mat, k):
    mat[k-1:10-k, [k-1, 10-k]] = k
    mat[[k-1, 10-k], k-1:11-k] = k
    
a = np.zeros((10,10), dtype = int)

for x in range(1,6):
    m(a,x)
'''    
mat = np.ones((10,10),np.uint8)
for i in range(1,10//2):
    mat[i:-i, i:-i] = i+1
print(mat)



[[1 1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Creare una funzione che trovi gli elementi comuni a due ndarray monodimensionali di lunghezza diversa.

In [3]:
import numpy as np
#nope
a = np.random.randint(0,10,(1,10))
b = np.random.randint(0,10,(1,20))
#c = a==b
c = np.intersect1d(a, b)

'''
print(np.isin(a,b))
'''
print(f"array 1 -> {a}")
print(f"array 2 -> {b}")
print(c)

array 1 -> [[5 3 3 9 6 1 1 2 0 8]]
array 2 -> [[8 6 6 4 9 1 4 5 1 3 6 5 5 8 2 0 7 6 2 9]]
[0 1 2 3 5 6 8 9]


### Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. 
### L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile. (chiedete l'altezza a tutti i compagni)

In [4]:
import numpy as np

altezze = np.random.uniform(1.50, 2, size=(17))
altezze = np.around(altezze, decimals=2)
#print(altezze)

media = altezze.mean()
deviazione = altezze.std()
#print(media, deviazione)

a = np.random.normal(media, deviazione, (1,17))
print(a)

print("\n")

altezze=np.random.normal(175,15,17)
print(np.around(altezze, decimals=2))  #(media, deviazione, quantità)

altezze= np.random.uniform(1.50, 2, size=(17))
print(np.around(altezze, decimals=2))

[[1.79172063 1.97733752 1.82253286 1.69806875 1.80074129 1.83500724
  1.70526781 1.71006537 1.74362147 1.8412561  1.75981366 1.94647703
  1.74169014 1.88503189 1.53109536 1.78117891 1.83401833]]


[168.39 194.06 170.37 169.2  182.83 183.96 178.75 175.46 149.57 152.87
 194.39 177.   203.01 155.86 159.25 178.83 166.05]
[1.57 1.88 1.71 1.62 1.9  1.75 1.96 1.8  1.91 1.86 1.92 1.58 1.56 1.67
 1.63 1.66 1.54]


## Trovare il valore più frequente presente in un array numpy. 

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
1


## Simulare diecimila partite ciascuna da 1000 lanci di una moneta: in quante partite si ha almeno 55% di croci sui 1000 lanci? 

In [6]:
'''
a = np.random.choice(["testa", "croce"], size=(10000,1000))
count = 0
for k in range (0, 9999):
    for element in a[k]:
        if element == "croce":
            count +=1
    if count >= 550:
        print(f"partita {k} --> probabilità >= 55%")
    count = 0
'''
a = np.random.randint(0,2,size=(10000,1000))
perc = np.sum(a==0, axis=1) / 1000
print(f"Perc croce {perc}")
perc_giust = np.sum(perc >= 0.55)
print(f"perc maggiore {perc_giust}")


Perc croce [0.498 0.531 0.518 ... 0.518 0.49  0.501]
perc maggiore 9


## Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno. 

In [7]:
#%%timeit
a = np.random.randint(0,364,(1000,25))
#k = 0
cC = 0
for row in a:
    #k += 1
    u, c = np.unique(row, return_counts=True)
    dup = u[c > 1]
    if dup.size != 0:
        cC += 1
        #print(f"classe {k} ripetizione il/i giorno/i --> {dup}")
print(f"classi con ripetizione --> {cC}")

classi con ripetizione --> 566


## Inserire errrori in programma della centralina

In [8]:
n = 1000
dat = np.random.normal(19, 5, n)
dat[np.random.choice(np.arange(n), size=(20,), replace=False)] = 9999.9
print(dat)

[1.38788728e+01 1.63469998e+01 1.79285660e+01 1.56724300e+01
 1.79556573e+01 1.86444785e+01 2.20218097e+01 2.15930094e+01
 2.33007994e+01 2.03103044e+01 1.76201005e+01 2.53639689e+01
 2.38455204e+01 2.64454709e+01 2.34374107e+01 1.89919851e+01
 1.56990022e+01 1.29235227e+01 2.00743503e+01 1.89258812e+01
 1.91199505e+01 2.00140905e+01 2.32929043e+01 1.63050300e+01
 1.53992730e+01 1.62293299e+01 8.63189630e+00 1.31238391e+01
 1.37007249e+01 1.43522741e+01 1.40246015e+01 1.09576421e+01
 1.21523762e+01 1.86058163e+01 2.90231185e+01 1.78330215e+01
 2.34355519e+01 1.54201352e+01 1.39923648e+01 1.66972666e+01
 2.30972766e+01 1.19231198e+01 1.53264373e+01 1.78395823e+01
 2.30806413e+01 2.41385377e+01 1.42612772e+01 2.01892901e+01
 1.66866405e+01 1.94033513e+01 1.89260057e+01 2.50225024e+01
 1.04088196e+01 2.68234419e+01 1.21752667e+01 1.72642305e+01
 1.40407670e+01 9.99990000e+03 2.48833586e+01 2.25171810e+01
 1.09151302e+01 1.14530394e+01 2.05420261e+01 1.98933488e+01
 1.60725500e+01 2.115654

L'aeroporto JFK di New York vede transitare ogni giorno circa 200000 passeggeri. Ad ogni passeggero è misurata la temperatura. L'array temperature contiene tutte le temperature dei 200000 di passeggeri transitati il giorno 1 gennaio 2020, mentre l'array identificativi contiene la lista dei numeri identificativi della carta di viaggio per ciascun. passeggero. Trovare:

• il numero totale di passeggeri con temperatura maggiore di 37.5°C

• tutti gli identificativi dei passeggeri con temperatura maggiore di 37.5°C

Iniziamo creandoci un array di temperature, ricordandoci che la temperatura media di una persona sana è di 36.5°C e che i campioni avranno una distribuzione gaussiana.

In [12]:
import uuid

passeggeri = 20
array_id = []
temp_array = np.random.normal(36.5, 0.9, passeggeri)

print(temp_array)

print("\n")

array_id = np.array([uuid.uuid4() for _ in range(passeggeri)])
print(array_id)

print("\n")

full_array = dict(zip(array_id, temp_array))
print(full_array)

print("\n")

print(f"persone maggiore di 37.5 = {np.count_nonzero(temp_array > 37.5)}")

print("\n")

print(array_id[temp_array > 37.5])

[35.85398236 35.50421535 37.65097545 38.34277693 38.62808623 36.50365584
 35.33096715 35.05216521 37.2836052  35.73839459 36.6065211  36.75030201
 36.21911898 37.75405689 35.45090813 37.73274075 36.17076343 36.16224079
 36.40064133 34.11189736]


[UUID('670b9705-762e-4686-81f1-110145ac77a1')
 UUID('41d9e65b-4a58-489a-aed1-7c3755b5ee39')
 UUID('6d31b2cf-e65f-4105-b35b-f766b760a16f')
 UUID('1629aeb0-a7ac-4133-8d6d-6f24a37cccf0')
 UUID('11f3be80-3d2c-4ff2-af85-afa929c2f968')
 UUID('2efbef85-63b5-40b0-9b42-1c6c756a9292')
 UUID('aa4b04d2-2e53-49ff-a467-51ae47d8d7df')
 UUID('c9990313-cdb5-40ae-b7dd-5317c4fe1a88')
 UUID('70d914fd-250d-4892-9720-23f44dc77d3d')
 UUID('8ea24a90-3e3f-4674-b471-b898d8e533c6')
 UUID('b2f7261c-5285-40e0-97eb-9acba8dcc675')
 UUID('99a80797-b454-404b-b100-f96ca709cecb')
 UUID('12eae9db-68eb-4df5-9bab-d6dd765f31f4')
 UUID('ddaa60a3-cabe-42be-bbee-8fed8c630533')
 UUID('494a8119-7428-41dc-b5c1-912583a90132')
 UUID('84c84896-a222-4dc6-926b-dcccb0bedbb1')
 UUID('0025743c-5