## Disegnare un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [4]:
import numpy as np
'''
def m(mat, k):
    mat[k-1:10-k, [k-1, 10-k]] = k
    mat[[k-1, 10-k], k-1:11-k] = k
    
a = np.zeros((10,10), dtype = int)

for x in range(1,6):
    m(a,x)
'''    
mat = np.ones((10,10),np.uint8)
for i in range(1,10//2):
    mat[i:-i, i:-i] = i+1
print(mat)



[[1 1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Creare una funzione che trovi gli elementi comuni a due ndarray monodimensionali di lunghezza diversa.

In [5]:
import numpy as np
#nope
a = np.random.randint(0,10,(1,10))
b = np.random.randint(0,10,(1,20))
#c = a==b
c = np.intersect1d(a, b)

'''
print(np.isin(a,b))
'''
print(f"array 1 -> {a}")
print(f"array 2 -> {b}")
print(c)

array 1 -> [[3 4 2 8 1 7 5 7 1 9]]
array 2 -> [[5 0 5 5 8 9 0 5 8 5 7 6 4 2 9 8 2 8 8 7]]
[2 4 5 7 8 9]


### Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. 
### L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile. (chiedete l'altezza a tutti i compagni)

In [6]:
import numpy as np

altezze = np.random.uniform(1.50, 2, size=(17))
altezze = np.around(altezze, decimals=2)
#print(altezze)

media = altezze.mean()
deviazione = altezze.std()
#print(media, deviazione)

a = np.random.normal(media, deviazione, (1,17))
print(a)

print("\n")

altezze=np.random.normal(175,15,17)
print(np.around(altezze, decimals=2))  #(media, deviazione, quantità)

altezze= np.random.uniform(1.50, 2, size=(17))
print(np.around(altezze, decimals=2))

[[2.04339675 1.79706442 1.54726693 1.55474524 1.60587439 1.74024937
  1.78639989 1.90692531 1.68983983 1.76287135 1.7151798  1.61967935
  1.93243869 1.99996046 1.56292746 1.70461178 1.72332645]]


[190.97 176.8  175.74 178.66 196.94 156.25 185.35 197.15 161.   173.03
 204.08 185.26 171.52 159.18 187.62 198.16 196.09]
[1.68 1.88 1.98 1.61 1.7  1.53 1.74 1.94 1.72 1.81 1.61 1.93 1.8  1.69
 1.89 1.74 1.54]


## Trovare il valore più frequente presente in un array numpy. 

In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
1


## Simulare diecimila partite ciascuna da 1000 lanci di una moneta: in quante partite si ha almeno 55% di croci sui 1000 lanci? 

In [8]:
'''
a = np.random.choice(["testa", "croce"], size=(10000,1000))
count = 0
for k in range (0, 9999):
    for element in a[k]:
        if element == "croce":
            count +=1
    if count >= 550:
        print(f"partita {k} --> probabilità >= 55%")
    count = 0
'''
a = np.random.randint(0,2,size=(10000,1000))
perc = np.sum(a==0, axis=1) / 1000
print(f"Perc croce {perc}")
perc_giust = np.sum(perc >= 0.55)
print(f"perc maggiore {perc_giust}")


Perc croce [0.524 0.484 0.524 ... 0.482 0.496 0.473]
perc maggiore 7


## Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno. 

In [9]:
#%%timeit
a = np.random.randint(0,364,(1000,25))
#k = 0
cC = 0
for row in a:
    #k += 1
    u, c = np.unique(row, return_counts=True)
    dup = u[c > 1]
    if dup.size != 0:
        cC += 1
        #print(f"classe {k} ripetizione il/i giorno/i --> {dup}")
print(f"classi con ripetizione --> {cC}")

classi con ripetizione --> 579


## Inserire errrori in programma della centralina

In [10]:
n = 1000
dat = np.random.normal(19, 5, n)
dat[np.random.choice(np.arange(n), size=(20,), replace=False)] = 9999.9
print(dat)

[ 1.90448278e+01  1.97448027e+01  2.49094223e+01  2.83847052e+01
  1.21261944e+01  1.82002956e+01  2.94170061e+01  1.48408484e+01
  2.16240988e+01  1.60798371e+01  1.21267984e+01  1.60297689e+01
  2.18515424e+01  5.45167613e+00  1.99132623e+01  2.26086743e+01
  1.58825602e+01  2.08010407e+01  2.07995698e+01  2.31234276e+01
  2.01904373e+01  1.67955306e+01  2.78754440e+01  2.06902137e+01
  1.96940432e+01  2.67159629e+01  9.58656942e+00  2.54621550e+01
  2.56941721e+01  1.68253635e+01  2.12860567e+01  2.10954176e+01
  2.45283244e+01  6.69644822e+00  1.41912891e+01  1.46594833e+01
  1.79991261e+01  1.76489277e+01  1.44229565e+01  2.85998925e+01
  9.99990000e+03  2.25654536e+01  2.92402144e+01  1.76601586e+01
  2.00928849e+01  2.61022652e+01  2.68417577e+01  2.06804472e+01
  2.05623162e+01  1.66315937e+01  7.96622047e+00  2.19684888e+01
  2.01654534e+01  2.55314271e+01  1.19266568e+01  2.27867557e+01
  2.36907756e+01  2.15848155e+01  8.13032478e+00  2.12629667e+01
  2.31650161e+01  1.66076

L'aeroporto JFK di New York vede transitare ogni giorno circa 200000 passeggeri. Ad ogni passeggero è misurata la temperatura. L'array temperature contiene tutte le temperature dei 200000 di passeggeri transitati il giorno 1 gennaio 2020, mentre l'array identificativi contiene la lista dei numeri identificativi della carta di viaggio per ciascun. passeggero. Trovare:

• il numero totale di passeggeri con temperatura maggiore di 37.5°C

• tutti gli identificativi dei passeggeri con temperatura maggiore di 37.5°C

Iniziamo creandoci un array di temperature, ricordandoci che la temperatura media di una persona sana è di 36.5°C e che i campioni avranno una distribuzione gaussiana.

In [11]:
import uuid

passeggeri = 20
array_id = []
temp_array = np.random.normal(36.5, 0.9, passeggeri)

print(temp_array)

print("\n")

array_id = np.array([uuid.uuid4() for _ in range(passeggeri)])
print(array_id)

print("\n")

full_array = dict(zip(array_id, temp_array))
print(full_array)

print("\n")

print(f"persone maggiore di 37.5 = {np.count_nonzero(temp_array > 37.5)}")

print("\n")

print(array_id[temp_array > 37.5])

[35.7008856  35.91271526 36.58232432 36.53293057 37.33562205 35.77215685
 34.95368997 34.89450229 36.31473501 36.54180482 35.67814471 37.02895948
 36.96285824 35.81902285 35.39962678 35.5261544  35.17346505 36.81158707
 35.22067347 37.24146927]


[UUID('940fea08-b97d-4463-98e2-a8c941d9c664')
 UUID('b72ba598-7602-4f9b-97cd-af3fae91bc10')
 UUID('221b40ef-d90c-442c-875d-5076e1be4994')
 UUID('c1d7cef7-90b6-4a37-a36e-3315684cc59e')
 UUID('d44a9cd7-e4d5-4dff-a200-1c9c41bfba54')
 UUID('349b6ee3-530a-4d7f-997d-c2223b7604c7')
 UUID('2c22d055-f348-4038-b082-a803f5cd793a')
 UUID('1439b831-84d6-474d-b542-5023c3f2dece')
 UUID('04c0e5df-6c1c-4604-8be0-2f9e7a5cb33d')
 UUID('01765e51-46ba-4a44-946e-0bc750b50ab4')
 UUID('df371277-2d5f-4068-b7b6-a1192e4eaaa1')
 UUID('9c81753e-e51d-4674-94d2-9cb6d12b2881')
 UUID('6ed83f86-97c5-4b04-a694-36cfa613bfdb')
 UUID('2708577d-336d-4c39-8c78-ce596780a967')
 UUID('c35e1883-6d5d-4795-b8c2-429ddcf44e33')
 UUID('5407e208-0bb7-47a5-98ca-b32f5773737d')
 UUID('107f2b7e-3

## trova il massimo locale

In [12]:
import numpy as np

a = np.array([0,2,1,1,3,2])
print(a[np.logical_and(a > np.roll(a, 1), a > np.roll(a, -1))])

#estremi esclusi
array= np.array([0,2,1,1,3,2])
arrayDx= np.roll(array,1)[1:-1]   #trasla il vettore di 1 a destra
arraySx= np.roll(array,-1)[1:-1]  #trasla il vettore di (-1 a destra) ovvero 1 a sinistra
a= array[1:-1]
print(a[np.logical_and(a> arrayDx, a>arraySx)])

[2 3]
[2 3]


In [13]:
import numpy as np

nNumeri = 3000
seq = [1,2,3]
a = np.random.randint(10, size=nNumeri)
print(a)

for i in range(len(a)-len(seq)+1):
    if np.all((a[i:i+len(seq)] == seq)) == True:
        print(i)
        
print('a', a)
mat = np.array([a[i:len(seq)+i] for i in range(len(a)-len(seq)+1)])
print(mat)
print("\n")
print(np.argwhere(np.all(seq == mat, axis=1)).flatten())

[7 5 9 ... 6 6 4]
554
a [7 5 9 ... 6 6 4]
[[7 5 9]
 [5 9 1]
 [9 1 0]
 ...
 [1 0 6]
 [0 6 6]
 [6 6 4]]


[554]


In [14]:
import numpy as np

#con estremi inclusi:
array = np.array([0,2,1,1,3,4])
arrayDx = np.roll(array, 1)
arraySx = np.roll(array, -1)
print(array[np.logical_and(array > arrayDx, array > arraySx)], '\n')

#Con estremi esclusi:
array = np.array([0,2,1,1,3,4])
arrayDx = np.roll(array, 1)
arraySx = np.roll(array, -1)
mat = np.array([array, arrayDx, arraySx]).reshape(3,-1)
#mat = np.stack((array, arrayDx, arraySx), axis=0)
print(mat, '\n')
massimo = np.argmax(mat[:,1:-1], axis = 0) #indice del massimo rispetto all'asse 0
print(f'I massimi locali si trovano nella posizione: {(np.argwhere(massimo==0)+1).flatten()}, i loro valori sono: {array[(np.argwhere(massimo==0)+1).flatten()]}')
#print(array[(np.argwhere(massimo==0)+1).flatten()]) #argwhere trova gli indici della matrice in cui vale quella condizione, flatten ritrasforma la matrice in array

[2 4] 

[[0 2 1 1 3 4]
 [4 0 2 1 1 3]
 [2 1 1 3 4 0]] 

I massimi locali si trovano nella posizione: [1], i loro valori sono: [2]


In [15]:
import numpy as np

nNumeri = 30000
seq = [1,2,3]
array = np.random.randint(10, size = nNumeri)
print(array)

for i in range(len(array)-len(seq)+1):
    #print(array[i:i+len(seq)] == seq)
    if np.all((array[i:i+len(seq)] == seq))==True: #la all controlla se tutta quella riga è True
        print(i)
        
#Seconda soluzione
mat = np.array([array[i:len(seq)+i] for i in range(len(array)-len(seq)+1)])
print('\n',mat,'\n')
#print(sequenza == mat)
print(np.argwhere(np.all(seq == mat, axis=1)).flatten())

[0 8 1 ... 1 1 2]
959
1889
3894
4090
5990
6318
7399
9093
9187
9372
9700
10417
11029
14244
14619
15230
17515
20942
21318
21889
22188
23272
24033
24158
25919
25976
27994
28287
28728
28843
29143

 [[0 8 1]
 [8 1 3]
 [1 3 0]
 ...
 [2 3 1]
 [3 1 1]
 [1 1 2]] 

[  959  1889  3894  4090  5990  6318  7399  9093  9187  9372  9700 10417
 11029 14244 14619 15230 17515 20942 21318 21889 22188 23272 24033 24158
 25919 25976 27994 28287 28728 28843 29143]
