# Creare ndarray da liste, tuple es intervalli

In [1]:
import numpy as np

a1 = np.array((1, 2, 3)) #array da tupla
a2 = np.array([1.6, -1, 3], np.uint8) #array da lista con specifica di tipo
a3 = np.arange(10, dtype = float) #array da range [0...STOP] con passo 1 e specifica di tipo
a4 = np.arange(4, 10, 2) #array da range [START...STOP] con passo 2
a5 = np.linspace(0, 10, 5) #array di 5 numeri equalmente distribuiti in [START...STOP]

print("a1:", a1)
print("a2:", a2)
print("a3:", a3)
print("a4:", a4)
print("a5:", a5)

a1: [1 2 3]
a2: [  1 255   3]
a3: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a4: [4 6 8]
a5: [ 0.   2.5  5.   7.5 10. ]


# Creare un vettore di tutti zero, uno o di un valore specificato

In [2]:
a6 = np.zeros(5, dtype = np.uint) #array di 0 con specifica di tipo (per default float64)
a7 = np.ones(5) #array di 1 (per default float64)
a8 = np.zeros((2,3)) #array di 0 con dimensioni specificate

print(a6, '\n')
print(a7, '\n')
print(a8, '\n')
a8.fill(3)
print(a8)


[0 0 0 0 0] 

[1. 1. 1. 1. 1.] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[3. 3. 3.]
 [3. 3. 3.]]


In [8]:
import numpy as np

a1 = np.random.rand(2,3) #matrice 2x3 con numeri casuali in [0...1]
a2 = (np.random.rand([1,7],size = [2,3])) #matrice 2x3 con numeri casuali in [0...1]



print(a1)
print(a2)

TypeError: rand() got an unexpected keyword argument 'size'

In [5]:
import random
import numpy as np

print(np.random.choice(['testa', 'croce'], size = 8, p = [0.8, 0.2])) #probabilità maggiore su testa
print(np.random.choice(['qui', 'quo', 'qua'], size = 3, replace = False)) #senza ripetizioni

ndarray = np.array([[1,2], [10,20], [100,200]])
print(ndarray)
print('Numero di dimensioni', np.ndim(ndarray))

#modifica della struttura
ndarray.shape = (6,1)
print(ndarray)
math = ndarray.reshape(2,-1)
print(math)

['testa' 'croce' 'testa' 'testa' 'testa' 'testa' 'testa' 'croce']
['qua' 'quo' 'qui']
[[  1   2]
 [ 10  20]
 [100 200]]
Numero di dimensioni 2
[[  1]
 [  2]
 [ 10]
 [ 20]
 [100]
 [200]]
[[  1   2  10]
 [ 20 100 200]]
