# Note introduttive

## Gli assert

Ti è stato chiesto di scrivere un programma per controllare un reattore nucleare. Il reattore produce tanta energia, ma ha anche bisogno di almeno 20 metri d’acqua per raffreddarsi, e il tuo programma deve regolare il livello dell’acqua. Senza acqua sufficiente, rischi una fusione. Non ti senti esattamente all’altezza del compito, e cominci a sudare

Con un certo nervosismo scrivi il codice. Controlli e ricontrolli il programma, credi che sia tutto giusto.

Il giorno dell’inaugurazione, il reattore viene fatto partire. Inaspettatamente, il livello dell’acqua scende a 5 metri, e inizia la reazione. Seguono spettacoli pirotecnici al plutonio.

Avremmo potuto evitare tutto ciò? A volte crediamo sia tutto giusto ma per qualche motivo ci ritroviamo variabili con valori inattesi. Il programma sbagliato descritto qua sopra, in Python avrebbe potuto essere così:

    # ci serve acqua per raffreddare il nostro reattore nucleare
    livello_acqua = 40 #  sembra sufficiente

    print("livello_acqua: ", livello_acqua)

    # tanto codice
    # tanto codice

    livello_acqua = 5  # abbiamo dimenticato questa riga nefasta !
    print("ATTENZIONE: livello acqua basso! ", livello_acqua)

    # tanto codice
    # tanto codice
    # dopo tanto codice potremmo non sapere se ci sono le condizioni necessarie
    # affinchè tutto funzioni correttamente

    print("fai partire reattore nucleare")

    >>livello_acqua:  40
    >>ATTENZIONE: livello acqua basso!  5
    >>fai partire reattore nucleare

Come potremmo migliorarlo? Guardiamo come funziona il comando assert, che va scritto facendolo seguire da una condizione booleana.

`assert True` non fa assolutamente niente:

    print("prima")
    assert True
    print("dopo")

    >>prima
    >>dopo

Invece, `assert False` blocca l’esecuzione del programma, lanciando un’eccezione di tipo AssertionError (notare come "dopo" non venga stampato):

    print("prima")
    assert False
    print("dopo")

    >>prima
    >>---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-7-a871fdc9ebee> in <module>()
    ----> 1 assert False


Per migliorare il programma precedente, potremmo usare assert così:

    # ci serve acqua per raffreddare il nostro reattore nucleare
    livello_acqua = 40 #  livello sufficiente

    print("livello_acqua: ", livello_acqua)

    # tanto codice
    # tanto codice

    livello_acqua = 5  # abbiamo dimenticato questa riga nefasta !
    print("ATTENZIONE: livello acqua basso! ", livello_acqua)

    # tanto codice
    # tanto codice
    # dopo tanto codice potremmo non sapere se ci sono le condizioni necessarie
    # affinchè tutto funzioni correttamente
    # quindi prima di fare cose pericolose, è sempre meglio fare un controllo !
    # se l'assert fallisce (cioè se l'espressione booleana è False)
    # l'esecuzione si blocca subito
    
    assert livello_acqua >= 20
    print("fai partire reattore nucleare")

    >>livello_acqua:  40
    >>ATTENZIONE: livello acqua basso!  5
    >>---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-14-9019745468f3> in <module>
         29 # se l'assert fallisce (cioè se l'espressione booleana è False)
         30 # l'esecuzione si blocca subito
    ---> 31 assert livello_acqua >= 20
         32
         33 print("fai partire reattore nucleare")

    AssertionError:

## Quando usare gli assert?

Il caso qua sopra è volutamente esagerato, ma mostra come un controllo in più a volte impedisca disastri.

NOTA: Gli assert sono un modo molto spiccio di fare controlli, tanto che Python permette anche di ignorarli durante l’esecuzione per migliorare le performance, chiamando python con il parametro -O come in:

    python -O mio_file.py

Ma se le performance non sono un problema (nel caso del reattore qui sopra), conviene riscrivere il programma usando un **if e lanciando esplicitamente una Exception**:

    # ci serve acqua per raffreddare il nostro reattore nucleare
    livello_acqua = 40 #  seems ok
    print("livello_acqua: ", livello_acqua)

    # tanto codice
    # tanto codice
    
    livello_acqua = 5  # abbiamo dimenticato questa riga nefasta !
    print("ATTENZIONE: livello acqua basso! ", livello_acqua)

    # tanto codice
    # tanto codice
    # dopo tanto codice potremmo non sapere se ci sono le condizioni necessarie
    # affinchè tutto funzioni correttamente
    # quindi prima di fare cose pericolose, è sempre meglio fare un controllo !
    
    if livello_acqua < 20:
        raise Exception("Livello acqua troppo basso !")  # l'esecuzione si blocca subito

    print("fai partire reattore nucleare")

    >>livello_acqua:  40
    >>ATTENZIONE: livello acqua basso!  5

    >>---------------------------------------------------------------------------
    Exception                                 Traceback (most recent call last)
    <ipython-input-16-02382ff90f5a> in <module>
         28 # quindi prima di fare cose pericolose, è sempre meglio fare un controllo !
         29 if livello_acqua < 20:
    ---> 30     raise Exception("Livello acqua troppo basso !")  # l'esecuzione si blocca subito
         31
         32 print("fai partire reattore nucleare")

    Exception: Livello acqua troppo basso !

## Usare gli assert per testare

Si usa spesso gli assert per fare dei test, cioè per verificare che una funzione si comporti come ci si attende.

Per esempio, per questa funzione:

    def somma(x, y):
        s = x + y
        return s

Ci si attende che somma(2,3) dia 5. Possiamo scrivere in Python questa attesa usando un assert:
    
    assert somma(2,3) == 5

Se somma è implementata correttamente: somma(2,3) ci dara 5 e l’espression booleana somma(2,3) == 5 darà True.  assert True verrà eseguita senza produrre alcun risultato, lasciando proseguire l’esecuzione del programma

Viceversa, se somma NON è implementata correttamente come in questo caso:

    def somma(x,y):
        return 666

somma(2,3) produrrà il numero 666 l’espression booleana somma(2,3) == 5 darà quindi False assert False interromperà l’esecuzione del programma, lanciando un eccezione di tipo AssertionError

# Esercizi NUMPY

Negli esercizi seguenti si utilizzerà il meccanismo degli allert per verificare se hai scritto il codice in modo corretto, usando la funzione `np.allclose()` che ritorna True se tutti i valori nella prima matrice sono abbastanza vicini (cioè entro una certa tolleranza) ai corrispondenti nella seconda 
    
    assert np.allclose(a1, a2) 

Pertanto per risolverli, dovrai:

- sostituire la riga `raise Exception("TODO IMPLEMENT ME !")` con il corpo della funzione
- eseguire la cella

Se l’esecuzione della cella non lancia eccezioni, perfetto! Vuol dire che la funzione fa quello che ci si attende (gli assert quando vanno a buon fine non producono output)

Se invece vedi qualche AssertionError, probabilmente hai sbagliato qualcosa.

### quadro

✪✪✪ Restituisce una NUOVA matrice numpy di n righe e n colonne, in cui tutti  i valori sono a zero eccetto quelli sui bordi, che devono essere uguali a k
       

Per esempio, `quadro(4, 7.0)` deve dare:

```python
    array([[7.0, 7.0, 7.0, 7.0],
           [7.0, 0.0, 0.0, 7.0],
           [7.0, 0.0, 0.0, 7.0],
           [7.0, 7.0, 7.0, 7.0]])
```

In [55]:
import numpy as np

def quadro(n, k):
    '''
    a = np.zeros(n*n)
    a = a.reshape(n,n)
    a[:,0:n:n-1] = k
    a[0:n:n-1] = k
    print(a)'''
    a = np.zeros((n,n))
    a[[0,-1]] = k
    a[:,[0, -1]] = k
    print(a)
    return a
    

r1 = np.array( [[7.0, 7.0, 7.0, 7.0],
                [7.0, 0.0, 0.0, 7.0],
                [7.0, 0.0, 0.0, 7.0],
                [7.0, 7.0, 7.0, 7.0]])
# all_close ritorna True se tutti i valori nella prima matrice sono abbastanza vicini 
# (cioè entro una certa tolleranza) ai corrispondenti nella seconda 
assert np.allclose(quadro(4, 7.0), r1) 

r2 = np.array( [ [7.0] ])
assert np.allclose(quadro(1, 7.0), r2) 

r3 = np.array( [ [7.0, 7.0],
                 [7.0, 7.0]])
assert np.allclose(quadro(2, 7.0), r3) 

[[7. 7. 7. 7.]
 [7. 0. 0. 7.]
 [7. 0. 0. 7.]
 [7. 7. 7. 7.]]
[[7.]]
[[7. 7.]
 [7. 7.]]


### scacchiera

✪✪✪ RITORNA una NUOVA matrice numpy di `n` righe e `n` colonne, in cui le celle si alternano tra zero e uno.

Esempio: `scacchiera(4)` deve dare:
   
```python
    array([[1.0, 0.0, 1.0, 0.0],
           [0.0, 1.0, 0.0, 1.0],
           [1.0, 0.0, 1.0, 0.0],
           [0.0, 1.0, 0.0, 1.0]])
```

In [69]:
import numpy as np

def scacchiera(n):  
    a = np.zeros((n,n))
    a[0::2, 0::2] = 1
    a[1::2, 1::2] = 1
    print(a)
    return a

r1 = np.array( [ [1.0, 0.0, 1.0, 0.0],
                 [0.0, 1.0, 0.0, 1.0],
                 [1.0, 0.0, 1.0, 0.0],
                 [0.0, 1.0, 0.0, 1.0] ])

# all_close ritorna True se tutti i valori nella prima matrice sono abbastanza vicini 
# (cioè entro una certa tolleranza) ai corrispondenti nella seconda 
assert np.allclose(scacchiera(4), r1) 

r2 = np.array( [ [1.0] ])
assert np.allclose(scacchiera(1), r2) 

r3 = np.array( [ [1.0, 0.0],
                 [0.0, 1.0] ])
assert np.allclose(scacchiera(2), r3) 

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[1.]]
[[1. 0.]
 [0. 1.]]


### media_righe

✪✪✪ Prende una matrice numpy n x m  e RITORNA una NUOVA matrice numpy di una sola colonna in cui i valori sono la media dei valori nelle corrispondenti righe della matrice in input

Esempio:

Input: matrice 5x4

```
3 2 1 4
6 2 3 5
4 3 6 2
4 6 5 4
7 2 9 3
```

Output: matrice 5x1

```
(3+2+1+4)/4 
(6+2+3+5)/4
(4+3+6+2)/4
(4+6+5+4)/4
(7+2+9+3)/4
```

In [11]:
import numpy as np

def media_righe(mat):
    mat = np.mean(mat, axis=1)
    mat = mat.reshape(-1,1)  #-1 per dire "fattelo tu", non so il numero di righe quindi lo ometto
    print(mat)
    
    '''
    matrice = np.array([mat[i].mean() for i in range(mat.shape[0])])
    matrice = matrice.reshape(-1,1)
    print(matrice)
    '''
    return mat
  
m1 = np.array([  [5.0]  ])
r1 = np.array([  [5.0]  ])
assert np.allclose(media_righe(m1), r1)

m2 = np.array([ [5.0, 3.0] ])
r2 = np.array([ [4.0]  ])
assert np.allclose(media_righe(m2), r2)

m3 = np.array(
    [[3,2,1,4],
     [6,2,3,5],
     [4,3,6,2],
     [4,6,5,4],
     [7,2,9,3]])

r3 = np.array([ [(3+2+1+4)/4],
                [(6+2+3+5)/4],
                [(4+3+6+2)/4],
                [(4+6+5+4)/4],
                [(7+2+9+3)/4] ])

assert np.allclose(media_righe(m3), r3)

[[5.]]
[[4.]]
[[2.5 ]
 [4.  ]
 [3.75]
 [4.75]
 [5.25]]


### matrot 

✪✪✪ RITORNA una NUOVA matrice numpy che ha i numeri della matrice numpy  di input ruotati di una colonna. 

Per ruotati intendiamo che:

- se un numero nella matrice di input si trova alla colonna j, nella matrice  di output si troverà alla colonna j+1 nella stessa riga.
- Se un numero si trova nell'ultima colonna, nella matrice di output si troverà nella colonna zeresima.

Esempio:

Se abbiamo come input 

```python
np.array(   [
                [0,1,0],
                [1,1,0],
                [0,0,0],
                [0,1,1]
            ])
```

Ci aspettiamo come output

```python
np.array(   [
                [0,0,1],
                [0,1,1],
                [0,0,0],
                [1,0,1]
            ])
```

In [12]:
import numpy as np

def matrot(matrice):
    '''
    mat = matrice.copy()
    mat[:,1:] = matrice[:,0:-1]
    mat[:,0] = matrice[:,-1]
    '''
    matrice = np.roll(matrice,1,axis=1)
    print(matrice)
    return matrice

m1 = np.array(  [ [1] ])
r1 = np.array( [  [1]  ])
assert np.allclose(matrot(m1), r1)

m2 = np.array(  [ [0,1] ])
r2 = np.array( [ [1,0] ])
assert np.allclose(matrot(m2), r2)

m3 = np.array([ [0,1,0] ])
r3 = np.array([ [0,0,1] ])
assert np.allclose(matrot(m3), r3)

m4 = np.array(  [[0,1,0],
                 [1,1,0]])
r4 = np.array(  [[0,0,1],
                 [0,1,1]])
assert np.allclose(matrot(m4), r4)


m5 = np.array([ [0,1,0],
                [1,1,0],
                [0,0,0],
                [0,1,1]])
r5 = np.array([ [0,0,1],
                [0,1,1],
                [0,0,0],
                [1,0,1]])
assert np.allclose(matrot(m5), r5)

[[1]]
[[1 0]]
[[0 0 1]]
[[0 0 1]
 [0 1 1]]
[[0 0 1]
 [0 1 1]
 [0 0 0]
 [1 0 1]]


### disp

✪✪✪ Prende una matrice Numpy `mat` di dimensioni`nrighe` x `ncol` contenente numeri interi  in input e RITORNA una NUOVA matrice numpy di dimensioni `nrighe` x `ncol` che è come quella originale, ma nelle celle che contenevano numeri pari adesso ci saranno numero dispari ottenuti sommando `1` al numero pari esistente.

Esempio:

```python

disp(np.array( [ 
                    [2,5,6,3],
                    [8,4,3,5],
                    [6,1,7,9]
               ]))
```
Deve dare in output

```python
array([[ 3.,  5.,  7.,  3.],
       [ 9.,  5.,  3.,  5.],
       [ 7.,  1.,  7.,  9.]])
```

In [17]:
import numpy as np

def disp(mat):
    m = np.where(mat%2 == 0, mat+1, mat) #dove i numeri sono pari (prima parte) agiungi uno (seconda parte), altrimenti lascia invariato (terza parte)
    print(m)
    return m

m1 = np.array([ [2] ])
r1 = np.array([ [3] ])
assert np.allclose(disp(m1), r1)
assert m1[0][0] == 2  # controlla non si stia modificando la matrice originale

m2 = np.array( [ [2,5,6,3],
                 [8,4,3,5],
                 [6,1,7,9]
               ])
r2 = np.array( [ [3,5,7,3],
                 [9,5,3,5],
                 [7,1,7,9]])
assert np.allclose(disp(m2), r2)

[[3]]
[[3 5 7 3]
 [9 5 3 5]
 [7 1 7 9]]


### radalt

✪✪✪ Prende una matrice numpy `mat` di dimensioni`nrighe` x `ncol` contenente numeri interi  in input e RITORNA una NUOVA matrice numpy di dimensioni `nrighe` x `ncol`, avente alle righe di **indice** pari i numeri della matrice originale moltiplicati per due, e alle righe di **indice** dispari gli stessi numeri della matrice originale

Esempio: 

```python
m  = np.array( [                      #  indice
                    [ 2, 5, 6, 3],    #    0     pari
                    [ 8, 4, 3, 5],    #    1     dispari
                    [ 7, 1, 6, 9],    #    2     pari
                    [ 5, 2, 4, 1],    #    3     dispari
                    [ 6, 3, 4, 3]     #    4     pari
               ])
```

Una chiamata a 

```python
radalt(m)
```

ritornerà la matrice numpy

```python
array([[ 4, 10, 12,  6],              
       [ 8,  4,  3,  5],              
       [14,  2, 12, 18],             
       [ 5,  2,  4,  1],
       [12,  6,  8,  6]])
```

In [23]:
import numpy as np

def radalt(mat):
    m = mat.copy()
    m[0::2] = mat[0::2]*2
    print(m)
    return m

# INIZIO TEST: NON TOCCARE !        

m1 = np.array([ [2] ])
r1 = np.array([ [4] ])
assert np.allclose(radalt(m1),r1)
assert m1[0][0] == 2  # controlla non si stia modificando la matrice originale

m2 = np.array( [ [ 2, 5, 6],
                 [ 8, 4, 3]])
r2 = np.array( [ [ 4,10,12],
                 [ 8, 4, 3]])
assert np.allclose(radalt(m2), r2)

m3 = np.array( [ [ 2, 5, 6, 3],
                 [ 8, 4, 3, 5],
                 [ 7, 1, 6, 9],
                 [ 5, 2, 4, 1],
                 [ 6, 3, 4, 3] ])
r3 = np.array( [ [ 4,10,12, 6],
                 [ 8, 4, 3, 5],
                 [14, 2,12,18],
                 [ 5, 2, 4, 1],
                 [12, 6, 8, 6] ])
assert np.allclose(radalt(m3), r3) 
# FINE TEST 

[[4]]
[[ 4 10 12]
 [ 8  4  3]]
[[ 4 10 12  6]
 [ 8  4  3  5]
 [14  2 12 18]
 [ 5  2  4  1]
 [12  6  8  6]]


### somma_alterna

✪✪✪ MODIFICA la matrice numpy in input (n x n), sommando a tutte le righe dispari le righe pari. Per esempio:

```python
    m = [[1.0, 3.0, 2.0, 5.0],
         [2.0, 8.0, 5.0, 9.0],
         [6.0, 9.0, 7.0, 2.0],
         [4.0, 7.0, 2.0, 4.0]]
    somma_alterna(m)
```    

adesso `m` dovrebbe essere :

```python
    m = [[1.0, 3.0, 2.0, 5.0],
         [3.0, 11.0,7.0, 14.0],
         [6.0, 9.0, 7.0, 2.0],
         [10.0,16.0,9.0, 6.0]]
```    

In [29]:
import numpy as np

def somma_alterna(mat):
    mat[1::2] += mat[0::2]
    print(mat)
    #mat[1::2] = np.add(mat[1::2], mat[0::2])
    return mat
  
  
m1 = np.array( [ [1.0, 3.0, 2.0, 5.0],
                       [2.0, 8.0, 5.0, 9.0],
                       [6.0, 9.0, 7.0, 2.0],
                       [4.0, 7.0, 2.0, 4.0] ]) 

r1 = np.array( [ [1.0, 3.0, 2.0, 5.0],
                 [3.0, 11.0,7.0, 14.0],
                 [6.0, 9.0, 7.0, 2.0],
                 [10.0,16.0,9.0, 6.0] ])

somma_alterna(m1)
assert np.allclose(m1, r1)  # controlla che abbiamo MODIFICATO la matrice originale

m2 = np.array( [ [5.0] ])
r2 = np.array( [ [5.0] ])
somma_alterna(m1)                  
assert np.allclose(m2, r2)  

m3 = np.array( [ [6.0, 1.0],
                 [3.0, 2.0] ])                    
r3 = np.array( [ [6.0, 1.0],
                 [9.0, 3.0] ])
somma_alterna(m3)
assert np.allclose(m3, r3) 

[[ 1.  3.  2.  5.]
 [ 3. 11.  7. 14.]
 [ 6.  9.  7.  2.]
 [10. 16.  9.  6.]]
[[ 1.  3.  2.  5.]
 [ 4. 14.  9. 19.]
 [ 6.  9.  7.  2.]
 [16. 25. 16.  8.]]
[[6. 1.]
 [9. 3.]]


### media_meta

✪✪✪ Prende in input una matrice numpy con un numero pari di colonne, e RITORNA in output una matrice numpy 1x2: il primo elemento sarà la media della metà sinistra della matrice, il secondo elemento sarà la media della metà destra.

Ingredienti:

- per ottenere il numero di colonne diviso 2 come numero intero, usare l'operatore `//`

In [32]:
def media_meta(mat):
    col = mat.shape[1]//2 #divisione intera delle colonne
    m = np.array([np.mean(mat[:,0:col]), 
                  np.mean(mat[:,col:])])
    print(m)
    return m

# INIZIO TEST
m1 = np.array([[3,2,1,4],
              [6,2,3,5],
              [4,3,6,2],
              [4,6,5,4],
              [7,2,9,3]])

r1 = np.array([(3+2+6+2+4+3+4+6+7+2)/10, (1+4+3+5+6+2+5+4+9+3)/10  ])

assert np.allclose( media_meta(m1), r1)
# FINE TEST

[3.9 4.2]


## matxarr

✪✪✪ Prende una matrice numpy n x m e un ndarray di m elementi, e RITORNA una NUOVA matrice numpy in cui i valori di ogni colonna della matrice di input sono moltiplicati per il corrispondente valore dell'array di n elementi.


In [36]:
def matxarr(mat, arr):
    m = mat*arr   #fa dropcasting        
    print(m)
    return m
    
m1 = np.array( [ [3,2,1],
                 [6,2,3],
                 [4,3,6],
                 [4,6,5] ] )
a1 = [5, 2, 6]
r1 = [ [3*5, 2*2, 1*6],
       [6*5, 2*2, 3*6],
       [4*5, 3*2, 6*6],
       [4*5, 6*2, 5*6] ]
assert np.allclose(matxarr(m1,a1), r1)

[[15  4  6]
 [30  4 18]
 [20  6 36]
 [20 12 30]]


### quadranti

✪✪✪ Data una matrice `2n * 2n`, dividere la matrice in 4 parti quadrate uguali 
(vedi esempio per capire meglio) e RESTITUIRE una NUOVA matrice `2 * 2`
contente la media di ogni quadrante

Si assume che la matrice sia sempre di dimensioni pari

SUGGERIMENTO: per dividere per 2 e ottenere un numero intero, usare l'operatore // 


Esempio:
```
 1, 2 , 5 , 7
 4, 1 , 8 , 0
 2, 0 , 5 , 1 
 0, 2 , 1 , 1 
```
si divide in 

```
  1, 2 | 5 , 7
  4, 1 | 8 , 0
----------------- 
  2, 0 | 5 , 1 
  0, 2 | 1 , 1 
```

e si restituisce 

```
  (1+2+4+1)/ 4  | (5+7+8+0)/4                        2.0 , 5.0 
  -----------------------------            =>        1.0 , 2.0 
  (2+0+0+2)/4   | (5+1+1+1)/4  
```

In [39]:
import numpy as np

def quadranti(mat):
    col = mat.shape[1]//2
    row = mat.shape[0]//2
    m = np.array([[np.mean(mat[:row, :col]), np.mean(mat[:row, col:])],
                [np.mean(mat[row:, :col]), np.mean(mat[row:, col:])]])
    print(m)
    return m
    
    
# INIZIO TEST - NON TOCCARE !
m1 = np.array( [ [3.0, 5.0],
                 [4.0, 9.0] ])
r1 = np.array([  [3.0, 5.0],
                 [4.0, 9.0],
              ])
assert np.allclose(quadranti(m1),r1)

m2 = np.array( [ [1.0, 2.0 , 5.0 , 7.0],
                 [4.0, 1.0 , 8.0 , 0.0],
                 [2.0, 0.0 , 5.0 , 1.0], 
                 [0.0, 2.0 , 1.0 , 1.0] ])
r2 = np.array( [ [2.0, 5.0],
                 [1.0, 2.0] ] )
assert np.allclose(quadranti(m2),r2)
# FINE TEST

[[3. 5.]
 [4. 9.]]
[[2. 5.]
 [1. 2.]]
